version: '3'

services:
    mongo:
        image: mongo
        container_name: apidbs
        environment:
        - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        volumes:
          - ./mongo:/data/db
        ports:
          - "27017:27017"